version: '3.4'

services:

  orders.webapi:
    image: ${DOCKER_REGISTRY-}orderswebapi
    build:
      context: .
      dockerfile: src/Orders/WebApi/Dockerfile
    expose:
      - "5000"
    ports:
      - 5000:5000

  # Sharing one DB server for all services
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: booking
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
